import { Injectable, Logger, OnModuleInit } from '@nestjs/common';
import { ConfigService } from '@nestjs/config';
import { StateService } from '../../core/state/state.service';
import { ShellService } from '../../core/shell/shell.service';
import * as fs from 'fs-extra';
import * as path from 'path';

// Defines the structure of our state config from the panel
// This should match the backend API response structure
interface DhcpConfig {
    subnets: Array<{
        subnet: string;
        netmask: string;
        gateway: string;
        rangeStart: string;
        rangeEnd: string;
        dns: string;
    }>;
    hosts: Array<{
        mac: string;
        ip: string;
        hostname?: string;
    }>;
}

@Injectable()
export class DhcpService implements OnModuleInit {
    private readonly logger = new Logger(DhcpService.name);
    private readonly configPath = '/etc/dnsmasq.d/agent-managed.conf';

    constructor(
        private readonly stateService: StateService,
        private readonly shellService: ShellService,
        private readonly configService: ConfigService
    ) { }

    onModuleInit() {
        this.stateService.getConfig().subscribe(config => {
            if (config && config.dhcp) {
                this.reconcile(config.dhcp);
            }
        });
    }

    async reconcile(dhcpData: DhcpConfig) {
        this.logger.log('Reconciling DHCP Configuration...');

        try {
            const configContent = this.generateDnsmasqConfig(dhcpData);

            // Check if file content changed
            let currentContent = '';
            try {
                currentContent = await fs.readFile(this.configPath, 'utf8');
            } catch (e) {
                // File doesn't exist, ignore
            }

            if (currentContent.trim() !== configContent.trim()) {
                this.logger.log(`DHCP Config drift detected. updating ${this.configPath}`);

                // Write new config
                // In dev mode or without root, this might fail. 
                // We should handle that via a try-catch and maybe write to a temp file first.
                // For now, assume we have permissions or write to a local dev path if needed.
                const targetPath = this.configService.get('DEV_MODE') ? './agent-managed.conf' : this.configPath;

                await fs.writeFile(targetPath, configContent);

                // Reload Dnsmasq
                if (!this.configService.get('DEV_MODE')) {
                    await this.shellService.reloadService('dnsmasq');
                    this.logger.log('dnsmasq reloaded successfully.');
                }
            } else {
                this.logger.debug('DHCP Config is in sync.');
            }

        } catch (e) {
            this.logger.error('Failed to reconcile DHCP config', e);
        }
    }

    private generateDnsmasqConfig(data: DhcpConfig): string {
        let conf = '# Auto-generated by Agent. Do not edit manually.\n\n';

        // Get agent network configuration
        const agentIp = this.configService.get<string>('AGENT_IP') || this.getLocalIp();
        const agentPort = this.configService.get<string>('PORT') || '3000';
        const dhcpInterface = this.configService.get<string>('DHCP_INTERFACE') || 'ens19';

        // Interface binding
        conf += `# Network interface\n`;
        conf += `interface=${dhcpInterface}\n`;
        conf += `bind-interfaces\n\n`;

        // Logging
        conf += `# Logging\n`;
        conf += `log-dhcp\n`;
        conf += `log-facility=/var/log/dnsmasq-pxe.log\n\n`;

        // Add Subnets
        // dnsmasq: dhcp-range=set:tag,start,end,netmask,lease
        if (data.subnets && data.subnets.length > 0) {
            for (const sub of data.subnets) {
                conf += `# Subnet: ${sub.subnet}\n`;
                conf += `dhcp-range=${sub.rangeStart},${sub.rangeEnd},${sub.netmask},12h\n`;
                conf += `dhcp-option=option:router,${sub.gateway}\n`;
                conf += `dhcp-option=option:dns-server,${sub.dns || '8.8.8.8'}\n`;
                conf += '\n';
            }
        } else {
            // Fallback: Use environment variables if no subnets synced from Panel
            const fallbackRange = this.configService.get<string>('DHCP_RANGE');
            const fallbackGateway = this.configService.get<string>('DHCP_GATEWAY') || '10.15.0.1';
            const fallbackDns = this.configService.get<string>('DHCP_DNS') || '8.8.8.8';

            if (fallbackRange) {
                // Format: "10.15.0.100,10.15.0.200,255.255.255.0"
                conf += `# Fallback DHCP Range (from env)\n`;
                conf += `dhcp-range=${fallbackRange},12h\n`;
                conf += `dhcp-option=option:router,${fallbackGateway}\n`;
                conf += `dhcp-option=option:dns-server,${fallbackDns}\n\n`;
            }
        }

        // Add Static Hosts
        // dnsmasq: dhcp-host=mac,ip,hostname
        if (data.hosts) {
            conf += '# Static Reservations\n';
            for (const host of data.hosts) {
                const mac = host.mac.toLowerCase();
                conf += `dhcp-host=${mac},${host.ip}${host.hostname ? ',' + host.hostname : ''}\n`;
            }
        }

        // PXE Boot Options
        // Two-stage boot: 
        // 1. Non-iPXE clients get ipxe.efi/undionly.kpxe
        // 2. iPXE clients chain to our Agent's /pxe/boot endpoint
        conf += '\n# PXE Boot Options\n';
        conf += 'enable-tftp\n';
        conf += 'tftp-root=/srv/tftp\n';
        conf += '\n';

        // Detect iPXE vs regular PXE
        conf += '# iPXE detection: iPXE sends user-class "iPXE" or option 175\n';
        conf += 'dhcp-match=set:ipxe,175\n';
        conf += 'dhcp-userclass=set:ipxe,iPXE\n';
        conf += '\n';

        // Set next-server to this Agent
        conf += `# Boot server address\n`;
        conf += `dhcp-option=option:server-ip-address,${agentIp}\n`;
        conf += '\n';

        // For non-iPXE clients: serve iPXE binary via TFTP
        conf += '# Stage 1: Non-iPXE clients load iPXE binary from TFTP\n';
        conf += 'dhcp-boot=tag:!ipxe,undionly.kpxe\n';
        conf += 'dhcp-boot=tag:!ipxe,tag:efi64,ipxe.efi\n';
        conf += '\n';

        // For iPXE clients: chain to our HTTP endpoint
        conf += '# Stage 2: iPXE clients chain to Agent PXE endpoint\n';
        conf += `dhcp-boot=tag:ipxe,http://${agentIp}:${agentPort}/pxe/boot\n`;
        conf += '\n';

        return conf;
    }

    /**
     * Attempt to get local IP address for PXE boot server.
     * Falls back to localhost if unable to determine.
     */
    private getLocalIp(): string {
        try {
            const os = require('os');
            const interfaces = os.networkInterfaces();

            // Prefer interfaces in order: ens*, eth*, en*
            const preferredPrefixes = ['ens', 'eth', 'en', 'bond'];

            for (const prefix of preferredPrefixes) {
                for (const [name, addrs] of Object.entries(interfaces)) {
                    if (name.startsWith(prefix) && addrs) {
                        for (const addr of addrs as any[]) {
                            if (addr.family === 'IPv4' && !addr.internal) {
                                this.logger.log(`Detected Agent IP: ${addr.address} (${name})`);
                                return addr.address;
                            }
                        }
                    }
                }
            }

            // Fallback: any non-internal IPv4
            for (const addrs of Object.values(interfaces)) {
                if (addrs) {
                    for (const addr of addrs as any[]) {
                        if (addr.family === 'IPv4' && !addr.internal) {
                            this.logger.log(`Detected Agent IP (fallback): ${addr.address}`);
                            return addr.address;
                        }
                    }
                }
            }
        } catch (e) {
            this.logger.warn('Failed to detect local IP', e);
        }

        return '127.0.0.1';
    }
}
